id = "git"
name = "git"
description = "Distributed version control."
categories = ["essentials"]
tier = "core"
capabilities = []
dependencies = []
setup_script = "setup-essentials.sh"

[packages]
pacman = ["git"]
aur = []
